routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth;
use Laratrust\Laratrust;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::post('/', 'Auth\LoginController@login');

Route::get('/', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('/logout', 'Auth\LoginController@logout');
Route::get('/password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm');
Route::post('/password/confirm', 'Auth\ConfirmPasswordController@confirm');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::post('/password/reset','Auth\ResetPasswordController@reset');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('/register', 'Auth\RegisterController@register');
Route::get('/register', 'Auth\RegisterController@showRegistrationForm');


Route::group(['middleware' => ['auth', 'verified']], function () {

    Route::resource('users', 'UserController')->names([
        '/users' => 'users',
        '/users/{user}/edit' => 'users.edit',
        '/users/create' => 'users/create',
        '/users/{user}/update' => 'users.update',
        '/users/{user}' => 'user.delete'
    ]);

});

/*     Route::resource('users', 'UserController', ['middleware' => ['role:admin|manager']])->names([
        '/users' => 'users',
        '/users/{user}/edit' => 'users.edit',
        '/users/create' => 'users/create',
        '/users/{user}/update' => 'users.update',
        '/users/{user}' => 'user.delete'
    ]);

*/

app/Permission.php
<?php

namespace App;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    public $guarded = [];
}

app/Role.php
<?php

namespace App;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;
use Laratrust\Traits\LaratrustUserTrait;


class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'user_id', 'role_id', 'user_type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->toDayDateTimeString();
    } */

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    
}

app/Http/Controllers/DatatablesController.php
<?php

namespace App\Http\Controllers;

use Yajra\DataTables\Html\Builder;

class DatatablesController extends Controller
{
    public function index(Builder $builder) 
    {
        if (request()->ajax()) {
            return DataTables::of(User::query())->toJson();
        }
        
        $html = $builder->columns([
                    ['data' => 'id', 'name' => 'id', 'title' => 'Id'],
                    ['data' => 'name', 'name' => 'name', 'title' => 'Name'],
                    ['data' => 'email', 'name' => 'email', 'title' => 'Email'],
                    ['data' => 'created_at', 'name' => 'created_at', 'title' => 'Created At'],
                    ['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'Updated At'],
                ]);

        return view('users.index', compact('html'));
    }
}   

/** 
 
function(Builder $builder) {
    if (request()->ajax()) {
        return DataTables::of(User::query())->toJson();
    }

    $html = $builder->columns([
                ['data' => 'id', 'name' => 'id', 'title' => 'id'],
                ['data' => 'name', 'name' => 'name', 'title' => 'Имя'],
                ['data' => 'email', 'name' => 'email', 'title' => 'Email'],
                ['data' => 'created_at', 'name' => 'created_at', 'title' => 'Создан'],
                ['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'Обновлен'],
            ]);
           

    return view('users.index', compact('html'));
}); 

*/

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Yajra\DataTables\Html\Builder;
use App\DataTables\UsersDataTable;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\DB;


class UserController extends Controller
{
    protected $arrRole = ['admin', 'manager', 'employee'];

    public function index(User $user, UsersDataTable $dataTable) 
    {   
        if (request()->ajax()) {
            return Datatables::of(User::select(['id', 'name', 'email', 'created_at', 'updated_at']))
            ->editColumn('action', function($user) {
                return view('users.views.action', ['user' => $user]);
            })
            ->editColumn('created_at', function ($request) {
                return $request->created_at; /** getter */
            })
            ->editColumn('updated_at', function ($request) {
                return $request->updated_at;
            })
            ->make(true);
        }
        /*if (Auth::user()->hasRole('admin|manager')){ */
            return $dataTable->render('users.index');
        
    }

    public function store(UserRequest $request, User $user)
    {
        User::create($request->all());
        flash()->success('Пользователь успешно создан');
        return redirect()->action('UserController@index');
    }

    public function destroy(User $user)
    {   
        flash()->success('Пользователь успешно удален');
        return $user->delete();
    }

    public function edit(User $user)
    {   $nameRole = DB::table("role_user")
            ->where('user_id', '=', $user->id)
            ->join('roles', 'roles.id', '=', 'role_user.role_id') 
            ->select("roles.name")
            ->first();
        return view('users/edit', ['user' => $user, 'roles' => DB::select('select name from roles'), 'nameRole' => $nameRole]);
    }

    public function update(Request $request, User $user)
    {
        $requestAll = $request->all();

        $arrRole = $this->arrRole;
        if (isset($requestAll['role'])) {
            foreach ($arrRole as $role) {
                if ($user->hasRole($role) == true) {
                    $user->detachRole($role);
                } 
            }
            $user->attachRole($requestAll['role']);
        }
        if ($requestAll['password'] == null){   
            unset($requestAll['password']);
        }
        $user->update($requestAll);   
        flash()->success('Пользователь успешно отредактирован');
        return redirect()->action('UserController@index');
    } 

    public function create()
    {
        return view('users/create');
    }

}


/*     
$arrRole = ['admin', 'manager', 'employee'];
foreach ($arrRole as $role)
{
    if (Auth::user()->hasRole($role) == true) {
        dd($role);
    } 
} 
*/ 

resources/views/home.blade.php
<html>
    <head>
        <style>
            .krug {
                height: 300px;
                width: 300px;
                border-radius: 100%;
                background-color:rgb(187, 48, 48);
                position: relative;
            }
            .krug_v_kruge {
                height: 150px;
                width: 150px;
                border-radius: 100%;
                background-color: rgb(194, 194, 51);
                position: absolute;
                top: 25%;
                left: 25%;
            }
        </style>
    </head>
    <body>
        <div class="krug">
            <div class="krug_v_kruge">
            </div>
        </div>
    <body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/login.blade.php
@extends('adminlte::auth.login')

resources/views/register.blade.php
@extends('adminlte::auth.register')

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('content')

<div class="col-md-6">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Создать пользователя</h3>
        </div>
        <form action="{{ URL::route('users.store') }}" method="post">
            @csrf
            <div class="card-body">
                <div class="form-group">     
                    <div class="form-group">
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">Имя</label>
                            <input class="form-control {{ ($errors->has('name')) ? 'is-invalid' : null  }}" type="text" name="name" id="inputName" placeholder="Введите имя">
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                            <input class="form-control {{ ($errors->has('email')) ? 'is-invalid' : null  }}" type="email" name="email" id="inputEmail" placeholder="Введите email">
                        </div>
                        <div class="form-group">
                            <label for="inputPassword" class="col-sm-2 control-label">Пароль</label>
                            <input class="form-control {{ ($errors->has('password')) ? 'is-invalid' : null  }}" type="password" name="password" id="inputPassword" placeholder="Введите пароль">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Создать</button>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('content') 

<div class="col-md-6">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Форма редактирования</h3>
        </div>
        <form action="{{ URL::route('users.update', ['user' => $user->id]) }}" method="post">
            @csrf
            <input type="hidden" name="_method" value="PUT">
            <div class="card-body">
                <div class="form-group">
                    <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label">Изменить имя</label>
                        <input class="form-control {{ ($errors->has('name')) ? 'is-invalid' : null  }}" type="text" name="name" id="inputName" value="{!! $user->name !!}">
                    </div>
                    <div class="form-group">
                        <label for="inputEmail" class="col-sm-4 control-label">Изменить email</label>
                        <input class="form-control {{ ($errors->has('email')) ? 'is-invalid' : null  }}" type="email" name="email" id="inputEmail" value="{!! $user->email !!}">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-4 control-label">Изменить пароль</label>
                        <input class="form-control {{ ($errors->has('passwords')) ? 'is-invalid' : null  }}" type="password" name="password" id="inputPassword" placeholder="Введите новый пароль">
                    </div>
                    <div class="form-group">
                    <label class="col-sm-2 control-label">Изменить роль</label>
                    <select name="role" class="custom-select">
                        @foreach($roles as $role)
                            <option value="{{ $role->name }}">{{ $role->name }}</option>
                        @endforeach
                    </select>
                    </div>
                    <div class="form-group">
                        @if(isset($nameRole))
                            <b>Текущая роль: </b>{{ $nameRole->name }}
                        @endif
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Редактировать</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="testmessage" id="testmessage">
            @include('flash::message')
            </div>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Таблица пользователей</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    {!! $dataTable->table(['class' => 'table table-bordered table-hover']) !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script src="https://adminlte.io/themes/dev/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>


{!! $dataTable->scripts() !!}
<script>

function deleteItem(id) {
    var _token = $("input[name='_token']").val();
    $.ajax({
        type: "POST",
        url: '/users/'+id,
        data: '_method=DELETE&_token=' + _token,
        success: function (result) {
            console.log(result);
            $('#dataTableBuilder').DataTable().ajax.reload();
            $('#testmessage').text("@include('flash::message')");
        }
    });
    
}

$('#flash-overlay-modal').modal();

$('div.alert').not('.alert-important').delay(2000).slideUp(800);

</script>

@endsection

resources/views/users/views/action.blade.php
 
 @role('admin')
<button class="btn btn-danger" onclick="deleteItem({{ $user->id }})" id="button_datatables" type="button"><i class="fas fa-trash-alt"></i></button>

<a href="{{ URL::route('users.edit', ['user' => $user->id]) }}" ><button class="btn btn-success" ><i class='fas fa-user-edit'></i></button></a> 
@endrole